---
name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fileschanged:
    name: List files changed for pull request
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: diff
        run: |
          echo "Comparing head_commit ${{github.event.push.head_commit}} to base_ref ${{github.event.push.base_ref}}"
          git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin ${{github.event.pull_request.base.ref}}
          #
          # Run changes only for Typescript, JSON and TF files
          #
          echo "files=$(git diff --name-only origin/${{github.event.pull_request.base.ref}} | grep -e '\.ts' -e '\.json' -e '\.tf' | wc -l)" | tee -a "$GITHUB_OUTPUT"
    outputs:
      files: ${{ steps.diff.outputs.files }}
  lint:
    needs: fileschanged
    if: ${{ needs.fileschanged.outputs.files != 0}}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: |
          npm ci --no-audit --prefer-offline
      - name: lint
        run: npm run lint
      - name: format
        run: npm run check-format

  test:
    strategy:
      fail-fast: false
      matrix:
        vscode:
          - '1.88.0'
          - 'insiders'
          - 'stable'
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Since we are using a matrix, we need to check if files changed on the step level, not on the job level
      - name: Check if source files changed
        if: ${{ needs.fileschanged.outputs.files != 0}}
        run: |
          echo "we need to define a run key here, just to have a step defined"
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Set up Xvfb (Ubuntu)
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: matrix.os == 'ubuntu-latest'
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          tofu_version: 1.8.0
      - name: Tofu version
        run: tofu version
      - name: Clean Install Dependencies
        run: npm ci --no-audit --prefer-offline
      - name: Run Tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Run Tests
        run: npm test
        if: runner.os != 'Linux'
